# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-75209cac-04f0-490b-a870-d5a475a908a7";
      fsType = "xfs";
    };

  # 保留根目录加密（直到你后续用 TF 卡彻底重装），但不再加密 Swap
  boot.initrd.luks.devices."luks-75209cac-04f0-490b-a870-d5a475a908a7".device = "/dev/disk/by-uuid/75209cac-04f0-490b-a870-d5a475a908a7";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/07E2-5C9A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # ✅ 彻底禁用物理硬盘加密 Swap，全权交给内存 zramSwap
  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
